### ISSUE TITLE
Please give a description

### ISSUE THREAD

**Issue by Shicoder** [tum-vision/csd_lmnn#1]
As I reproduce your experiment,there were some errors .Could you give a detailed description of how to run this code  correctly.

**Comment by johny-c** [comment]
Hi Shicoder, could you tell me what error you get?

**Comment by Shicoder** [comment]
Hi,I get those errors  today.
1.The directory DIRS_TO_PATH defined in init_dataset.m(compute_for_set,point_desc,tools,utils,plot,thirdparty) is not the same as the folder directory that you upload(plot,point_desc,thirdparty,toplevel_func,utils).
2.I set the dataset path according to variable DATASETS_DIRS,but I don't know where the .obj files in the folder DIRS.MESHES point to are from.
3.When the code runs to "parfor i = 1: length (SHAPES)" under compute_LBprop.m, the following error "Error using mshlp_matrix (line 42) An UndefinedFunction error was thrown on the workers for 'meshlp'.  This might be because the filecontaining 'meshlp' is not accessible on the workers.  Use addAttachedFiles(pool, files) to specify the required files to be attached.  See the documentation for 'parallel.Pool/addAttachedFiles' for more details.." Occurs.  
Thanks.
Of course,it's really a fine work.I can not wait to implement it.

**Comment by johny-c** [comment]
So, you were right, about 1. There was a directory name that was wrong ("compute_for_set").  
2. You have to setup your data directories yourself in the file init_dataset.m. 
3. I'm not sure about this one. You may have to recompile the meshlp files for your platform. The included .mexa64 was compiled for Ubuntu Linux 64-bit. 

I created a README.md that I hope clarifies the usage.

**Comment by Shicoder** [comment]
Thanks for your help, these problem have been solved. @johny-c
